# Common build stage
FROM node:18-alpine as common-build-stage

COPY ./frontend ./app

WORKDIR /app

RUN npm i -g vite && npm i -g pnpm

RUN pnpm install && pnpm build

RUN ls -al

# RUN npm cache clean --force && npm install pm2 -g && npm install

# RUN npm prune --production

EXPOSE 3000

FROM common-build-stage as production-build-stage

# CMD ["pnpm", "deploy:prod", "&&", "sleep", "infinity"]