# Common build stage
FROM node:18-alpine as common-build-stage

COPY ./frontend ./app

WORKDIR /app

# RUN npm i -g pm2 --registry=https://registry.npm.taobao.org
RUN npm i -g pm2 && npm install -g pnpm
RUN pnpm install

# RUN npm cache clean --force && npm install pm2 -g && npm install

# RUN npm prune --production

EXPOSE 80

FROM common-build-stage as production-build-stage

CMD ["pnpm", "deploy:prod", "&&", "sleep", "infinity"]
