version: "3.8"
services:
  mysql:
      image: mysql:8.0
      environment:
        MYSQL_ROOT_PASSWORD: mysql123456
        MYSQL_DATABASE: uacl
        MYSQL_USER: mysql
        MYSQL_PASSWORD: mysql123456
      volumes:
        - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
        - ./mysql/data:/var/lib/mysql
        - ./mysql/init:/docker-entrypoint-initdb.d
      ports:
        - "3306:3306"
      restart: always