version: '3.8'

services:
  # MySQL服务
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # 根据需要设置root密码
      MYSQL_DATABASE: mydatabase         # 创建数据库
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  # 后端服务
  backend:
    build: ./backend                  # 假设后端Dockerfile在当前目录的backend文件夹下
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=mydatabase
    ports:
      - "8000:8000"

  # 前端服务
  frontend:
    build: ./frontend   # 假设前端构建文件在当前目录的frontend文件夹下
    depends_on:
      - backend
    ports:
      - "80:80"

# 定义卷
volumes:
  mysql-data:
    driver: local