servers:
  - url: http://localhost:9000/
    description: 开发环境API url

paths:
  /v1/permission/assertRolePermission:
    post:
      tags:
      - Permission
      summary: "给角色分配资源权限"
      parameters:
        - in: header
          name: jwt_token
          schema:
            type: string
          required: true
        - in: body
          name: requestBody
          schema:
            type: object
            required:
              - namespace
              - role_id
              - resource_ids
            properties:
              namespace:
                description: 项目组标识
                type: string
              role_id:
                description: 角色 ID
                type: number
              resource_ids:
                description: 资源 ID 集合
                type: array
                items: 
                  type: number
              describe:
                description: 描述
                type: string
      responses:
        200:
          description: "OK"
        500:
          description: "Server Error"
        default:
          description: "Server Error"
  /v1/permission/assertUserRole:
    post:
      tags:
      - Permission
      summary: "给用户分配角色"
      parameters:
        - in: header
          name: jwt_token
          schema:
            type: string
          required: true
        - in: body
          name: requestBody
          schema:
            type: object
            required:
              - namespace
              - user
            properties:
              namespace:
                description: 项目组标识
                type: string
              user:
                description: 用户标识
                type: string
              role_id:
                description: 角色 ID
                type: number
              role_ids:
                type: array
                items:
                  type: number
                description: 角色IDs
      responses:
        200:
          description: "OK"
        500:
          description: "Server Error"
        default:
          description: "Server Error"
  /v1/permission/cancelRolePermission:
    post:
      tags:
      - Permission
      summary: "取消角色已分配的资源权限"
      parameters:
        - in: header
          name: jwt_token
          schema:
            type: string
          required: true
        - in: body
          name: requestBody
          schema:
            type: object
            required:
              - namespace
              - role_id
            properties:
              namespace:
                description: 项目组标识
                type: string
              role_id:
                description: 角色 ID
                type: number
              resource_id:
                description: 资源 ID
                type: number
      responses:
        200:
          description: "OK"
        500:
          description: "Server Error"
        default:
          description: "Server Error"
  /v1/permission/cancelUserRole:
    post:
      tags:
      - Permission
      summary: "取消分配给用户的角色"
      parameters:
        - in: header
          name: jwt_token
          schema:
            type: string
          required: true
        - in: body
          name: requestBody
          schema:
            type: object
            required:
              - namespace
              - user
            properties:
              namespace:
                description: 项目组标识
                type: string
              user:
                description: 用户标识
                type: string
              role_id:
                description: 角色 ID
                type: number
              role_ids:
                type: array
                items:
                  type: number
                description: 角色IDs
      responses:
        200:
          description: "OK"
        500:
          description: "Server Error"
        default:
          description: "Server Error"
  /v1/permission/getRolePermissions:
    post:
      tags:
      - Permission
      summary: "获取角色分配资源权限"
      parameters:
        - in: header
          name: jwt_token
          schema:
            type: string
          required: true
        - in: body
          name: requestBody
          schema:
            type: object
            required:
              - namespace
              - role_id
            properties:
              namespace:
                description: 项目组标识
                type: string
              role_id:
                description: 角色 ID
                type: number
              current:
                description: 页码
                type: number
                default: 1
              pageSize:
                description: 每页条数
                type: number
                default: 10
      responses:
        200:
          description: "OK"
        500:
          description: "Server Error"
        default:
          description: "Server Error"
  /v1/permission/getSelfPermissions:
    post:
      tags:
      - Permission
      summary: "获取用户自身的所有权限"
      parameters:
        - in: header
          name: jwt_token
          schema:
            type: string
          required: true
        - in: body
          name: requestBody
          schema:
            type: object
            required:
              - namespace
            properties:
              namespace:
                description: 项目组标识
                type: string
              category:
                description: 资源分类
                type: string
                default: 'menu'
      responses:
        200:
          description: "OK"
        500:
          description: "Server Error"
        default:
          description: "Server Error"
  /v1/permission/getUserRoles:
    post:
      tags:
      - Permission
      summary: "【不可用】获取用户和角色关系的接口"
      parameters:
        - in: header
          name: jwt_token
          schema:
            type: string
          required: true
        - in: body
          name: requestBody
          schema:
            type: object
            required:
              - namespace
            properties:
              namespace:
                description: 项目组标识
                type: string
              user:
                description: 用户标识
                type: string
              role_id:
                description: 角色ID
                type: number
              role_ids:
                type: array
                items:
                  type: number
                description: 角色IDs
              userId:
                description: 用户Id
                type: number
              userIds:
                type: array
                items:
                  type: number
                description: 用户Ids
      responses:
        200:
          description: "OK"
        500:
          description: "Server Error"
        default:
          description: "Server Error"
  /v1/permission/updateRolePermissions:
    post:
      tags:
      - Permission
      summary: "【不可用】批量更新角色操作权限"
      parameters:
        - in: header
          name: jwt_token
          schema:
            type: string
          required: true
        - in: body
          name: requestBody
          schema:
            type: object
            required:
              - namespace
              - role_id
              - permissions
            properties:
              namespace:
                description: 所属项目组
                type: string
              role_id:
                description: 角色 ID
                type: number
              permissions:
                description: 权限配置信息
                type: array
                minItems: 1
                items:
                  type: object
                  required:
                    - resource_id
                  properties:
                    resource_id:
                      description: 资源 ID
                      type: number
                    describe:
                      description: 描述
                      type: string
      responses:
        200:
          description: "OK"
        500:
          description: "Server Error"
        default:
          description: "Server Error"
  /v1/permission/checkPermission:
    post:
      tags:
      - Permission
      summary: "【不可用】用户权限检测"
      parameters:
        - in: header
          name: jwt_token
          schema:
            type: string
          required: true
        - in: body
          name: requestBody
          schema:
            type: object
            required:
              - namespace
              - user
              - resource
            properties:
              namespace:
                description: 项目组标识
                type: string
              user:
                description: 用户标识
                type: string
              resource:
                description: 资源标识
                type: string
      responses:
        200:
          description: "OK"
        500:
          description: "Server Error"
        default:
          description: "Server Error"
schemes:
 - https
 - http