servers:
  - url: http://localhost:9000/
    description: 开发环境API url

paths:
  /v1/user:
    get:
      tags: 
      - User
      summary: "获取用户列表"
      parameters:
        - in: header
          name: jwt_token
          schema:
            type: string
          required: true
        - in: query
          name: namespace
          description: 项目名称
          required: true
          schema:
            type: string
        - in: query
          name: id
          description: 用户ID
          required: false
          schema:
            type: number
        - in: query
          name: user
          description: 用户名
          required: false
          schema:
            type: string
        - in: query
          name: roleName
          description: 支持角色名称查询用户
          required: false
          schema:
            type: string
          default: ""
        - in: query
          name: userName
          description: 支持用户名称查询用户
          required: false
          schema:
            type: string
          default: ""
        - in: query
          name: current
          description: 页码
          default: 1
          schema:
            type: number
        - in: query
          name: pageSize
          description: 每页条数
          default: 10
          schema:
            type: number
      responses:
        200:
          description: "OK"
        500:
          description: "Server Error"
    post:
      tags: 
      - User
      summary: "新增用户"
      parameters:
        - in: header
          name: jwt_token
          schema:
            type: string
          required: true
        - in: body
          name: requestBody
          schema:
            type: object
            required:
              - namespace
              - user
              - name
            properties:
              name:
                type: string
              namespace:
                type: string
              user:
                type: string
              job:
                type: string
              password:
                type: string
                default: '12345678'
              email:
                type: string
              phone_number:
                type: string
              role_ids:
                type: array
                items:
                  type: number
      responses:
        200:
          description: "OK"
        500:
          description: "Server Error"
    put:
      tags: 
      - User
      summary: "更新用户信息"
      parameters:
        - in: header
          name: jwt_token
          schema:
            type: string
          required: true
        - in: body
          name: requestBody
          schema:
            type: object
            required:
              - id
              - namespace
            properties:
              id:
                type: number
              namespace:
                type: string
                comments: "必选，不可更改"
              password:
                type: string
              name:
                type: string
              phone_number:
                type: string
              job:
                type: string
              email: 
                type: string
              role_ids:
                type: array
                items:
                  type: number
      responses:
        200:
          description: "OK"
        500:
          description: "Server Error"
    delete:
      tags: 
      - User
      summary: "删除用户"
      parameters:
        - in: header
          name: jwt_token
          schema:
            type: string
          required: true
        - in: body
          name: requestBody
          schema:
            type: object
            required:
              - namespace
              - id
              - user
            properties:
              namespace:
                type: string
              id:
                type: number
              user:
                type: string
      responses:
        200:
          description: "OK"
        500:
          description: "Server Error"
  /v1/userInfo:
    get:
      tags: 
      - User
      summary: "获取用户信息"
      parameters:
        - in: header
          name: jwt_token
          schema:
            type: string
          required: true
      responses:
        200:
          description: "OK"
        500:
          description: "Server Error"
  /v1/login:
    post:
      tags: 
      - User
      summary: "登陆"
      parameters:
        - in: body
          name: requestBody
          schema:
            type: object
            required:
              - user
              - namespace
              - password
            properties:
              namespace:
                type: string
                comments: "项目组名称"
              user:
                type: string
                comments: "用户名"
              password:
                type: string
                comments: "密码"
      responses:
        200:
          description: "OK"
        500:
          description: "Server Error"
  /v1/register:
    post:
      tags:
      - User
      summary: "【不可用】注册"
      description: "create a user"
      parameters:
        - in: body
          name: requestBody
          schema:
            type: object
            required:
              - username
              - password
              - email
              - authCode
            properties:
              username:
                type: string
              password:
                type: string
              authCode:
                type: string
              email:
                type: string
              phone:
                type: string
              jobId: 
                type: number
              job:
                type: string
      responses:
        200:
          description: "OK"
        500:
          description: "Server Error"
        default:
          description: "Server Error"
  /v1/email/code:
    post:
      tags: 
      - User
      summary: "【不可用】注册发送邮件验证码"
      parameters:
        - in: body
          name: requestBody
          schema:
            type: object
            required:
              - email
              - codeType
            properties:
              email:
                type: string
              codeType:
                type: number
      responses:
        200:
          description: "OK"
        500:
          description: "Server Error"
  /v1/reset/password:
    post:
      tags: 
      - User
      summary: "【不可用】重置用户密码"
      parameters:
        - in: header
          name: jwt_token
          schema:
            type: string
          required: true
        - in: body
          name: requestBody
          schema:
            type: object
            required:
              - id
              - email
              - authCode
              - password
            properties:
              id:
                type: number
              email:
                type: string
              authCode:
                type: number
              password:
                type: string
      responses:
        200:
          description: "OK"
        500:
          description: "Server Error"
schemes:
 - https
 - http
