name: Build and Push Multi-Arch Docker Images

on:
  push:
    branches:
      - "deploy/api"
    tags:
      - "*"

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub (with token)
        uses: docker/login-action@v2
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Docker Images
        uses: docker/build-push-action@v4
        with:
          context: ./backend/
          file: ./backend/Dockerfile.prod
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/uacl:${{ github.ref_name }}
            ${{ secrets.DOCKER_USERNAME }}/uacl:latest
          platforms: linux/amd64,linux/arm64

      - name: Post Build Success
        run: echo "Docker images built and pushed successfully!"
