name: API CI

on:
  push:
    branches: [ "main", "feature/*", "pre" ]
  pull_request:
    branches: [ "main", "pre" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # 设置时间戳环境变量
      - name: Set timestamp
        id: vars
        run: echo "TIMESTAMP=$(date +%s)" >> $GITHUB_ENV
      
      # 构建 Docker 镜像
      - name: Build the Docker image
        run: docker build . --file ./backend/Dockerfile.prod --tag uacl:${{ env.TIMESTAMP }}

      # 更换 Docker 名称
      - name: Rename the Docker image
        run: docker tag library/uacl:${{ env.TIMESTAMP }} ${{ secrets.DOCKER_REGISTRY }}/uacl/api:${{ env.TIMESTAMP }}
      
      # 登录 Docker Hub
      - name: Log in to Docker Hub
        run: docker login ${{ secrets.DOCKER_REGISTRY }} -u ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
      
      # 推送 Docker 镜像到 Docker Hub
      - name: Push the Docker image
        run: docker push ${{ secrets.DOCKER_REGISTRY }}/uacl/api:${{ env.TIMESTAMP }}
      
      # 在远程服务器执行脚本
      - name: Run remote script
        uses: appleboy/ssh-action@v0.1.5
        with: 
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          script: |
            sh /data/uacl/update_env.sh BACKENDTAG ${{ env.TIMESTAMP }}

            cd /data/uacl
            
            docker compose restart