name: fronted CI

on:
  push:
    branches: [ "feature/*", "pre" ]
  pull_request:
    branches: [ "feature/*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # 设置时间戳环境变量
      - name: Set timestamp
        id: vars
        run: echo "TIMESTAMP=$(date +%s)" >> $GITHUB_ENV

      - name: show dir
        run: ls -l
      
      # 构建 Docker 镜像
      - name: Build the Docker image
        run: docker build . --file ./frontend/Dockerfile.prod --tag uacl-frontend:${{ env.TIMESTAMP }}

      # 更换 Docker 名称
      - name: Rename the Docker image
        run: docker tag library/uacl-frontend:${{ env.TIMESTAMP }} ${{ secrets.DOCKER_REGISTRY }}/uacl/uacl-frontend:${{ env.TIMESTAMP }}
      
      # 登录 Docker Hub
      - name: Log in to Docker Hub
        run: docker login ${{ secrets.DOCKER_REGISTRY }} -u ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
      
      # 推送 Docker 镜像到 Docker Hub
      - name: Push the Docker image
        run: docker push ${{ secrets.DOCKER_REGISTRY }}/uacl/uacl-frontend:${{ env.TIMESTAMP }}
      
      # 在远程服务器执行脚本
      - name: Run remote script
        uses: appleboy/ssh-action@v0.1.5
        with: 
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          script: |
            sh /data/uacl/update_env.sh FRONTEDTAG ${{ env.TIMESTAMP }} 

            cd /data/uacl 
            
            docker compose restart 2>/dev/null